apiVersion: v2
name: agency
description: eTrip Agency Helm chart
type: application
version: 0.5.8
appVersion: 2.13.3-r23
dependencies:
- name: companies
  version: "0.2.4"
  condition: companies.enabled
