apiVersion: v2
name: agency
description: eTrip Agency Helm chart
type: application
version: 0.5.5
appVersion: 2.13.3-r18
dependencies:
- name: companies
  version: "0.2.3"
  condition: companies.enabled
