replicas:
  web: 1
  db: 2

# to override chart app version (advertised and tag)
# version: "2.1.20"

image:
  registry: eu.gcr.io/tripsol
  pullPolicy: IfNotPresent
  # # to override tag for all images
  # tag: "2.1-dev9"
  # # to override server image tag
  # serverTag: ""
  # # to override client image tag
  # clientTag: ""
  # # to override rescheck image tag
  # rescheckTag: ""

ingress:
  enabled: false
#   admin:
#     hostnames: 
#     - agency-ro-staging.dyn.tripsolutions.co.uk
#   rescheck:
#     hostnames: 
#     - rescheck-ro-staging.dyn.tripsolutions.co.uk
#   tls: true
#   annotations: 
#     cert-manager.io/cluster-issuer: letsencrypt-staging
#     external-dns.alpha.kubernetes.io/hostname: agency-ro-staging.dyn.tripsolutions.co.uk

agency:
  env: staging
  supportWidget: false
  forTV: false
  market: ro
  rescheck: true
  jwt: 
    https_only_cookies: null
    samesite: null
  cron:
    exchangerate:
      enabled: true
      source: bnr
      currencies: [USD, EUR, GBP, AUD, CAD, JPY, CHF, CNY]
      schedule: 25 0 * * *
    etripImport:
      enabled: false
      schedule: 0 */3 * * *
    e_factura:
      schedule: 0 1 * * *
  mondial:
    env: test # test or live
    # values below would be the defaults if env is set to live
    # auth_url: https://pro-allianz-partners.apis.allianz.com/jwtauth/accesstoken
    # contracts_url: https://services.emagin.eu/ws/offer/pricing/v3.0/contracts
    # issue_url: https://services.emagin.eu/ws/purchase/booking/v3.0
  flexitech:
    env: test
    # url: uat-api.flexitechsolutions.co.uk
  paysafe:
    env: test
    url: false # specify full URL to override env
  gate_e:
    env: test
    url: false # specify full URL to override env
  felloh:
    env: test
    url: false # specify full URL to override env
  pnrConverter: null
    # public_key: null
    # private_key: null
  stuba_api:
    env: test
    url: false # specify full URL to override env
  travel_gate:
    env: test
    url: false # specify full URL to override env
  e_factura:
    enabled: false
    auth_url: https://logincert.anaf.ro
    api_url: https://api.anaf.ro
    webservice_url: https://webservicesp.anaf.ro
    client_id: client_id
    client_secret: client_secret
    vat_search_url: https://webservicesp.anaf.ro/PlatitorTvaRest/api/v8/ws/tva
  freescout:
    enabled: false
    api_url: https://helpdesk.tripsolutions.co.uk/api
    api_key: null
    mailbox_id: null
    user_id: null
  travelify:
    enabled: false
    url: https://api.travelify.io
    application_id: NULL
    private_key: NULL
  anaf:
    enabled: false
    vat_search_url: https://webservicesp.anaf.ro/PlatitorTvaRest/api/v8/ws/tva
  tinymce_key: null
  eurolife:
    enabled: false
    url: https://testpartners.eurolife-asigurari.ro:5651/api
    #username: username
    #password: password
    #api_key: apiKey
  cors:
    # enable CORS for the websites (list clients)
    free: false
    websites: []
    # urls:
    #  - https://www.etripagency.ro
    #  - https://etripagency.ro 
    #  - https://www.etrip-agency.ro 
    #  - https://etrip-agency.ro
    #  - https://www.etripagency.co.uk
    #  - https://etripagency.co.uk
    #  - https://www.etrip-agency.co.uk
    #  - https://etrip-agency.co.uk 
    #  - https://www.etripagency.com 
    #  - https://etripagency.com 
    #  - https://www.etrip-agency.com 
    #  - https://etrip-agency.com
  companies:
    enabled: true
    # if we can access via local service, bypass ingress
    # defaults to externalApi
    internalApi: null
    # URL visible from outside world, use in browser
    # defaults to {{ frontend }}/api
    externalApi: null
    # companies UI, required for CORS
    frontend: null
    shared_secret:
      source: null
      value: null
  gunicorn:
    workers: 1
    threads: 4

mail:
  smtp_host: mail.tripsolutions.co.uk # kubernetes solution coming soon?
  default_sender: "ETrip Agency <noreply@etrip-agency.ro>"

db:
  parameters: 
    max_connections: "100"
    shared_buffers: 1GB
    temp_buffers: 32MB
    work_mem: 32MB 
    timezone: "Europe/Berlin"
    maintenance_work_mem: 32MB
    autovacuum_work_mem: 32MB
    temp_file_limit: 2GB
    effective_cache_size: 2GB
    vacuum_cost_delay: 20ms
    effective_io_concurrency: "1"
    jit: "on"
    log_autovacuum_min_duration: "5000"
    log_checkpoints: "off"
    log_connections: "off"
    log_disconnections: "off"
    log_min_duration_statement: "5000"
    log_statement: "none"

  volume:
    size: 5Gi
    # storageClass: standard
    # resizeInUseVolumes: true
    # pvcTemplate: {}
  
  # allowCloneFrom: <namespace>
  allowCloneFrom: null
  
  image:
    pullPolicy: IfNotPresent
    registry: ghcr.io/cloudnative-pg
    name: postgresql
    tag: 18.3-standard-trixie
  
  generateIssuer: true
    # true: generate a CA cert using provided caIssuer
    # false: use provided caIssuer as CA; as such, must not be a self-signing issuer
  caIssuer:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned

  # CNPG value templates
  # These are injected directly into the CNPG cluster config so for really
  # specific overrides you can redefine these
  # Alternatively, there are overlay dictionaries under .db.overrides
  # these allow you to override very specific rendered values without
  # redefining the whole template
  template: |
    bootstrap:
      {{- if eq .db.bootstrap.mode "normal" }}
      initdb:
        database: agency
        owner: agency
        localeCType: en_US.UTF-8
        localeCollate: en_US.UTF-8
        postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
        - CREATE EXTENSION IF NOT EXISTS "pgcrypto"
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE
      {{- else if eq .db.bootstrap.mode "recovery" }}
      recovery:
        database: agency
        owner: agency
        {{- with .db.bootstrap.recovery.recoveryTarget }}
        recoveryTarget: {{ . | toYaml | nindent 8 }}
        {{- end }}{{/* with .db.bootstrap.recovery.recoveryTarget */}}
        
        {{- if eq .db.bootstrap.recovery.source "plugin" }}
        source: fromPlugin
        {{- else if eq .db.bootstrap.recovery.source "backup" }}
        backup: {{ .db.bootstrap.recovery.backupName }}
        {{- end }}{{/* bootstrap.recovery.source */}}
      {{- else if eq .db.bootstrap.mode "clone" }}
      pg_basebackup:
        database: agency
        owner: agency
        source: fromCluster
      {{- end }}{{/* bootstrap.mode */}}

    {{- if and (eq .db.bootstrap.mode "recovery") (eq .db.bootstrap.recovery.source "plugin") }}
    externalClusters:
    - name: fromPlugin
      {{- $plugin := mergeOverwrite (deepCopy .db.backup.plugin) ( .db.bootstrap.recovery.pluginOverride | default dict ) }}
      plugin: {{ $plugin | toYaml | nindent 8 }}
    {{- else if eq .db.bootstrap.mode "clone" }}
    externalClusters:
    - name: fromCluster
      {{- if eq .db.bootstrap.clone.source "peer" }}
      connectionParameters:
        host: {{ .db.bootstrap.clone.name | default .releaseName }}-db-rw.{{ .db.bootstrap.clone.namespace | default .Release.Namespace }}
        user: streaming_replica
      {{- if .db.bootstrap.clone.namespace }}
      sslKey:
        name: {{ default .releaseName }}-db-clone-tls
        key: tls.key
      sslCert:
        name: {{ default .releaseName }}-db-clone-tls
        key: tls.crt
      sslRootCert:
        name: {{ default .releaseName }}-db-clone-tls
        key: ca.crt
      {{- else }}{{/* no namespace */}}
      sslKey:
        name: {{ .db.bootstrap.clone.name }}-db-replica-tls
        key: tls.key
      sslCert:
        name: {{ .db.bootstrap.clone.name }}-db-replica-tls
        key: tls.crt
      sslRootCert:
        name: {{ .db.bootstrap.clone.name }}-db-replica-tls
        key: ca.crt
      {{- end }}{{/* clone.namespace */}}
      {{- else if eq .db.bootstrap.clone.source "cluster" }}
      {{ .db.bootstrap.clone.cluster | toYaml | nindent 2 }}
      {{- end }}{{/* clone.source == cluster */}}
    {{- end }}{{/* bootstrap.mode == clone */}}
    {{ if .db.bootstrap.standby }}
    replica:
      enabled: true
      source: fromCluster
    {{- end }}{{/* bootstrap.standby */}}

    {{- with .db.backup }}{{- if .enabled }}
    backup:
      target: {{ .target | default "prefer-standby" }}

    plugins:
    - name: {{ .plugin.name }}
      isWALArchiver: true
      parameters: {{ .plugin.parameters | toYaml | nindent 8 }}
    {{- end }}{{- end }}

  overrides: null
  ## directly override rendered template values here

  bootstrap: 
    mode: normal
    ## * normal: bootstrap a new cluster
    ## * recovery: recover a cluster from a backup
    ## * clone: clone a live cluster using pg_basebackup

    recovery:
      source: plugin # one of: plugin, backup; to implement in the future: volumeSnapshot

      ## * plugin: recover from backup management plugin, defined under backup.plugin
      ## * with the overrides under recovery.pluginOverride when defined
      ## * backup: recover from a backup CRD, defined under recovery.backupName
      # pluginOverride:
      #   name: barman-cloud.cloudnative-pg.io
      #   parameters:
      #     barmanObjectName: wasabi-objectstore
      # backupName: <backup-name>
      ## recovery target as defined in CNPG docs
      # recoveryTarget:
      #   backupID: <backup-id>
      #   targetTLI: <timeline>
      #   targetLSN: <LSN>
      #   targetTime: <timestamp>
      #   targetXID: <xid>
      #   targetName: <name>
      #   targetImmediate: true|false
      #   exclusive: true|false
    clone:
      source: peer
      ## * peer - clone from another agency companies install with a CNPG operated cluster
      ##      at least one of namespace or name need to be defined
      ##      if cross-namespace cloning, mirror the replica-tls secret
      ## * cluster - clone from a custom cluster fully defined under clone.cluster
      # namespace: production
      # name: <agency-companies-install-name>
      # cluster: 
      #   connectionParameters:
      #     host: <hostname>
      #     user: <replication-user>
      #     sslMode: [disable|require|verify-ca|verify-full]
      #   password:
      #     name: <secret-name>
      #     key: <secret-key>
      #   sslKey:
      #     name: <secret-name>
      #     key: <secret-key>
      #   sslCert:
      #     name: <secret-name>
      #     key: <secret-key>
      #   sslRootCert:
      #     name: <secret-name>
      #     key: <secret-key>
    
    standby: false
    ## creates a standby cluster using the same source as the clone or recovery

  backup:
    enabled: false
    schedule: null # set to cron spec string to enable scheduled backups
    target: prefer-standby
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: wasabi-objectstore
        # serverName: <serverName> # optional, defaults to cluster name

  ## CNPG specific: affinity rules
  ## See CNPG docs for details: 
  ## https://cloudnative-pg.io/documentation/1.20/api_reference/#affinityconfiguration
  ## example:
  # affinity: 
  #   enablePodAntiAffinity: true
  #   topologyKey: kubernetes.io/hostname
  #   nodeSelector:
  #     kubernetes.io/postgres.prod: "true"
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: kubernetes.io/postgres.prod
  #           operator: In
  #           values:
  #           - "true"
  #   tolerations:
  #   - key: "node-role.kubernetes.io/master"
  #     operator: "Exists"
  #     effect: "NoSchedule"
  #   - key: "node.kubernetes.io/not-ready"
  #     operator: "Exists"
  #     effect: "NoExecute"
  #   - key: "node.kubernetes.io/unreachable"
  #     operator: "Exists"
  #     effect: "NoExecute"
  #   podAntiAffinityType: required
  #   additionalPodAntiAffinity: []
  #   additionalPodAffinity: []

  affinity: null

  # add a PodMonitor for the cluster, requires prometheus operator
  monitoring: false

resources:
  # don't override operator defaults
  db: {}
  web:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 50Mi
  api:
    limits:
      cpu: "2"
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 50Mi
  cron:
    limits:
      cpu: "2"
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 50Mi

# subchart config
companies:
  enabled: false

global:
  allowCloneFrom: null
  db_exporter:
    enabled: false
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    extraQueries:
      pg_replication:
        query:
          SELECT 
            CASE WHEN pg_is_in_recovery() 
            THEN extract(EPOCH FROM CURRENT_TIMESTAMP - 
                pg_last_xact_replay_timestamp()) 
            ELSE NULL END AS lag,
            pg_wal_lsn_diff(
              CASE WHEN pg_is_in_recovery()
              THEN pg_last_wal_replay_lsn() 
              ELSE pg_current_wal_lsn() END,
              '0/0') AS current_lsn;
        metrics:
        - lag: 
            usage: GAUGE
            description: Replication lag behind master in seconds
        - current_lsn:
            usage: COUNTER
            description: Current WAL/LSN stream location in bytes
