{{ if .Values.apiDeploy  -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-config
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "labels" . | nindent 4 }}
data:
  supervisor.conf: |
    [supervisord]
    user=root

    [program:fpm]
    user = root
    command = php-fpm8 -y /config/fpm.ini
    autorestart = true
    startretries = 5
    stopwaitsecs = 15

    [program:nginx]
    command = nginx -c /config/nginx.conf
    autorestart = true
    startretires = 5
    stopwaitsecs = 15
    
  etrip-nginx.conf: |
    user nginx;
    worker_processes {{ .Values.etrip.nginx.workers | default 1 }};
    error_log /dev/stderr warn;
    daemon off;
    events {}
    http {
      include /etc/nginx/mime.types;
      server_tokens off;
      sendfile on;
      tcp_nopush on;
      access_log /proc/1/fd/1 combined;
      set_real_ip_from 0.0.0.0/0;
      real_ip_header X-Forwarded-For;

      map $remote_user $webservice { 
        default webservice;
        {{- range $value := .Values.etrip.priority_api_users }}
        {{ $value }} webservice_prio;
        {{- end }}
      }

      upstream webservice {
          server localhost:{{ .Values.etrip.fpm.ws.port }} max_fails=64 fail_timeout=1s;
      }

      upstream webservice_prio {
          server localhost:{{ .Values.etrip.fpm.ws_prio.port }} max_fails=64 fail_timeout=1s;
      }

      server {
        listen *:80;
        server_name localhost;
        root /var/www/localhost/webapp;
        location @404 { internal; }
        index index.php;
        
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_index index.php;
        fastcgi_intercept_errors off;
        error_page 404 @404;
        include /etc/nginx/fastcgi.conf;
        location / {
          location ~ \.php {
            fastcgi_pass $webservice;

          }
        }

        location ~ ^/(status|ping)$ {
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_index index.php;
          include /etc/nginx/fastcgi_params;
          fastcgi_pass $webservice;
        }
      }
    }
  etrip-fpm.ini: |
    [global]
    daemonize = no

    {{- range $key, $val := .Values.etrip.fpm }}
    {{- if and (not $val.disabled) }}

    [fpm-{{$key}}]
    listen = {{ $val.port }}
    user = nginx
    group = nginx
    pm = {{ $val.mode | default "dynamic" }}
    pm.max_children = {{ $val.max }}
    pm.start_servers = {{ $val.start }}
    pm.min_spare_servers = {{ $val.low }}
    pm.max_spare_servers = {{ $val.high }}
    ping.path = /ping
    request_terminate_timeout = 300
    clear_env = no
    {{- with $val.phpValues -}}
    {{- range $pkey, $pval := . }}
    php_value[{{$pkey}}] = {{$pval}}
    {{- end }}{{end}}
    {{- with $val.phpAdminValues -}}
    {{- range $pkey, $pval := . }}
    php_admin_value[{{$pkey}}] = {{$pval}}
    {{- end }}{{end}}
    {{- end }}
    {{- end }}
{{- end -}}