{{- if .Values.etripng.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "labels" . | nindent 4 }}
data:
  config.yaml: |{{ .Values.etripng.config | toYaml | nindent 4 }}
{{- end }}
