{{- if .Values.etrip.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-fpm-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  jobLabel: app.kubernetes.io/instance
  podTargetLabels:
  - app.kubernetes.io/component
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
