{{- if .Values.ingress.enabled -}}
{{- $name := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- with .Values.ingress.admin }}
  {{- range .hostnames }}
  - host: {{ . | quote }}
    http:
      paths:
      {{- if $.Values.api.enabled }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-service
            port: 
              name: api
      {{- end }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-service
            port:
              name: etrip
  {{- end }}{{ end }}
  {{- range $key, $instance := .Values.b2b }}
  {{- $b2bIngress := index $.Values.ingress.b2b $key -}}
  {{- range $b2bIngress.hostnames }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /server
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-service
            port:
              name: etrip
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-service
            port: 
              name: b2b-{{ $key }}
  {{- end }}{{ end }}
  {{- if .Values.frontends.enabled }}
  {{- range $key, $val :=  .Values.ingress.frontends }}
  {{- range $host := $val.hostnames}}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-service
            port: 
              name: frontend-{{ $key }}
  {{- end}}{{ end }}{{ end }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- with .Values.ingress.admin }}
    {{- range .hostnames }}
    - {{ . | quote }}
    {{- end }}{{ end }}
    {{- range $key, $instance := .Values.b2b }}
    {{- $b2bIngress := index $.Values.ingress.b2b $key -}}
    {{- range $b2bIngress.hostnames }}
    - {{ . | quote }}
    {{- end }}{{ end }}
    {{- if .Values.frontends.enabled }}
    {{- range $key, $val :=  .Values.ingress.frontends }}
    {{- range $host := $val.hostnames}}
    - {{ $host | quote }}
    {{- end}}{{ end }}{{ end }}
    secretName: {{ $name }}-cert
  {{- end }}
{{- end }}
