{{- if or .Values.etrip.use_redis .Values.etripng.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        command:
        - /bin/sh
        - -c
        - kvrocks --bind 0.0.0.0 --requirepass $REDIS_PASSWORD
        image: apache/kvrocks:latest
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: session
        ports:
        - containerPort: 6666
          name: redis
          protocol: TCP
        resources:
          {{- toYaml .Values.resources.redis | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  type: ClusterIP
{{- end  -}}
