{{- if or .Values.etrip.use_redis (and (not .Values.db.use_operator) (not .Values.db.custom_install.password.useSecret) ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
{{- if and (not .Values.db.use_operator) (not .Values.db.custom_install.password.useSecret) }}
  dbpassword: {{ .Values.db.custom_install.password.clearText }}
{{- end}}
{{- if .Values.etrip.use_redis }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name ) ) }}
{{- if $secret }}
  session: {{ $secret.data.session }}
{{- else }}
  session: {{ randAlphaNum 32 | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- if and .Values.db.use_operator .Values.db.operator_install.allowCloneFrom }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- $clusterName := include "clusterName" . }}
  name: standby.{{ $clusterName }}.credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ .Values.db.operator_install.allowCloneFrom | quote }}
type: Opaque
data:
  username: {{ "standby" | b64enc }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "standby.%s.credentials" $clusterName) ) }}
  {{- if $secret }}
  password: {{ $secret.data.password }}
  {{- else }}
  password: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end }}