{{- if or .Values.etrip.use_redis .Values.etripng.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name ) ) }}
{{- if $secret }}
  session: {{ $secret.data.session }}
{{- else }}
  session: {{ randAlphaNum 32 | b64enc }}
{{- end }}
{{- end }}
