{{- if .Values.etrip.use_redis -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name ) ) }}
{{- if $secret }}
  session: {{ $secret.data.session }}
{{- else }}
  session: {{ randAlphaNum 32 | b64enc }}
{{- end }}
{{- end }}

{{- $db := mergeOverwrite .Values.db ( .Values.db.operator_install | default dict ) -}}
{{- $clusterName := include "clusterName" $ }}
{{- if $db.allowCloneFrom }}
---
apiVersion: v1
kind: Secret
metadata:

  name: standby.{{ $clusterName }}.credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ $db.allowCloneFrom | quote }}
type: Opaque
data:
  username: {{ "standby" | b64enc }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "standby.%s.credentials" $clusterName) ) }}
  {{- if $secret }}
  password: {{ $secret.data.password }}
  {{- else }}
  password: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end }}
