{{ if .Values.apiDeploy  -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  ports:
  - name: http
    port: 80
    targetPort: etrip
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  type: ClusterIP
{{- end }}