apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "companies.releaseName" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "companies.labels" . | nindent 4 }}
data:
  config.ini: |
    [app:companies]
    use = egg:cumulus_companies

    pyramid.reload_templates = false
    pyramid.debug_authorization = false
    pyramid.debug_notfound = false
    pyramid.debug_routematch = false
    pyramid.default_locale_name = en
    pyramid.includes = pyramid_beaker

    sqlalchemy.url = postgresql+psycopg2://companies:$PG_PASS@
        {{- include "companies.clusterName" . -}} /companies
    retry.attempts = 3

    jwt.private_key = ${SESSION_SECRET}
    {{- with .Values.companies.jwt.https_only_cookies }}
    jwt.https_only_cookie = {{ . }}
    {{- end }}
    {{- with .Values.companies.jwt.samesite }}
    jwt.samesite = {{ . }}
    {{- end }}
    jwt.expiration = 28800
    jwt.leeway = 300
    jwt.cookie_reissue_time = 1800
    jwt.cookie_accept_header = true
    jwt.cookie_prefer_header = true
    jwt.cookie_path = /api
    {{ if len .Values.companies.jwt.domains }}
    jwt.cookie_domains = {{ range .Values.companies.jwt.domains }} {{ . }} {{ end }}
    {{ end }}
    shared_secret = ${SHARED_SECRET}

    cache.regions = default, short_term, binary
    cache.default.type = memory
    cache.default.expire = 60

    cache.short_term.type = memory
    cache.short_term.expire = 3600
    cache.binary.type = file
    cache.binary.expire = 3600
    cache.binary.data_dir = /tmp/binary-cache/data
    cache.binary.lock_dir = /tmp/binary-cache/lock

    [pshell]
    setup = cumulus_companies.pshell.setup

    ###
    # wsgi server configuration
    ###

    [alembic]
    # path to migration scripts
    script_location = companies:alembic
    pyramid_config_file = /config/config.ini#companies
    file_template = %%(year)d%%(month).2d%%(day).2d_%%(rev)s
    # file_template = %%(rev)s_%%(slug)s

    [pipeline:main]
    pipeline = cors gzip companies

    [server:main]
    use = egg:gunicorn#main
    bind = 0.0.0.0:6543
    workers = 4
    forwarded_allow_ips = *

    [filter:gzip]
    use = egg:Paste#gzip
    compress_level = 6

    {{- with .Values.companies.cors }}
    {{- $policies := list }}
    
    [filter:cors]
    use = egg:wsgicors#middleware
    {{- $frontends := $.Values.companies.agency.cors }}
    {{- if and $.Values.companies.agency.frontend (not $frontends) }}
      {{- $frontends = list $.Values.companies.agency.frontend }}
    {{- end }}
    {{- if $frontends }}
    agency_origin = {{ $frontends | join " " }}
    {{- else }}{{ if $.Values.global }}{{ if $.Values.global.agency }}
      {{- $frontends := list }}
      {{- $tls := $.Values.global.agency.tls }}
      {{- $proto := ternary "https" "http" $tls }}
      {{- range $.Values.global.agency.admin.hostnames }}
        {{- $frontends = append $frontends (print $proto "://" . ) }}
      {{- end }}
    agency_origin = {{ $frontends | join " " }}
    {{- end }}{{ end }}{{ end }}
    agency_headers = *
    agency_expose_headers = *
    agency_methods = HEAD, OPTIONS, GET, POST, DELETE
    agency_credentials = true
    agency_maxage = 180
    {{- $policies = append $policies "agency" }}

    {{- if .websites }}
    website_origin = {{ range .websites -}} {{ . }} {{ end }}
    website_methods = GET
    website_maxage = 180
    {{- $policies = append $policies "website" }}
    {{- end }}

    {{ if .free }}
    {{- $policies = append $policies "free" }}
    free_origin = copy
    free_headers = *
    free_expose_headers = *
    free_methods = HEAD, OPTIONS, GET, POST, DELETE
    free_credentials = true
    free_maxage = 180
    {{- end }}

    policy = {{ $policies | join ", " }}
    {{- end }}

    [loggers]
    keys = root, cumulus_companies, sqlalchemy

    [handlers]
    keys = console

    [formatters]
    keys = generic

    [logger_root]
    level = INFO
    handlers = console

    [logger_cumulus_companies]
    level = DEBUG
    handlers =
    qualname = cumulus_companies

    [logger_sqlalchemy]
    level = WARN
    handlers =
    qualname = sqlalchemy.engine

    [handler_console]
    class = StreamHandler
    args = (sys.stderr,)
    level = NOTSET
    formatter = generic

    [formatter_generic]
    format = %(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s] %(message)s
