{{- if .Values.companies.auto_invoices.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "companies.releaseName" . }}-invoices
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "companies.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.companies.auto_invoices.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        cronjob-name: invoices
        {{- include "companies.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            cronjob-name: invoices
            {{- include "companies.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
          - name: cron-invoices
            {{- include "companies.pod" . | nindent 12 }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "companies.releaseName" . }}-secret
                  key: auth_pkey
            - name: SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "companies.releaseName" . }}-secret
                  key: shared_secret
          volumes:
          - name: config
            configMap:
              name: {{ include "companies.releaseName" . }}-config
              items:
              - key: config.ini
                path: app/config.ini
          {{- if eq .Values.db.provider "cnpg" }}
          - name: ssl-cert
            secret:
              secretName: {{ include "companies.releaseName" . }}-db-app-tls
              defaultMode: 416
          {{- end }}
{{- end }}
