{{- $db := .Values.db -}}
{{- if or (eq $db.provider "cnpg") (eq $db.bootstrap.mode "transition")  -}}
{{- $releaseName := include "companies.releaseName" . -}}
{{- $labels := include "companies.labels" . -}}
{{- if $db.generateIssuer }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $releaseName }}-db-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  isCA: true
  commonName: {{ $releaseName }}-db
  dnsNames:
    {{- range $mode := (list "rw" "r" "ro") }}
    - {{ $releaseName }}-db-{{ $mode }}
    - {{ $releaseName }}-db-{{ $mode }}.{{ $.Release.Namespace }}
    - {{ $releaseName }}-db-{{ $mode }}.{{ $.Release.Namespace }}.svc
    - {{ $releaseName }}-db-{{ $mode }}.{{ $.Release.Namespace }}.svc.cluster.local
    {{- end }}
  issuerRef: {{ toYaml $db.caIssuer | nindent 4 }}
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: {{ $releaseName }}-db-ca
  secretTemplate:
    labels:
      cnpg.io/reload: "true"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $releaseName }}-db-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  ca:
    secretName: {{ $releaseName }}-db-ca
---
{{- else }}
{{- /*
  We need a server certificate generated by the caIssuer
*/}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $releaseName }}-db-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  ca: {{ toYaml $db.caIssuer | nindent 4 }}
  commonName: {{ $releaseName }}-db
  dnsNames:
    {{- range $mode := (list "rw" "r" "ro") }}
    - {{ $releaseName }}-db-{{ $mode }}
    - {{ $releaseName }}-db-{{ $mode }}.{{ $.Release.Namespace }}
    - {{ $releaseName }}-db-{{ $mode }}.{{ $.Release.Namespace }}.svc
    - {{ $releaseName }}-db-{{ $mode }}.{{ $.Release.Namespace }}.svc.cluster.local
    {{- end }}
  issuerRef: {{ toYaml $db.caIssuer | nindent 4 }}
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: {{ $releaseName }}-db-cert
  secretTemplate:
    labels:
      cnpg.io/reload: "true"
---
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $releaseName }}-db-replica
spec:
  commonName: streaming_replica
  {{- if $db.generateIssuer }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ $releaseName }}-db-issuer
  {{- else }}
  issuerRef: {{ toYaml $db.caIssuer | nindent 4 }}
  {{- end }}
  secretName: {{ $releaseName }}-db-replica-tls
  secretTemplate:
    labels:
      cnpg.io/reload: "true"
    {{- if $db.allowCloneFrom }}
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ $db.allowCloneFrom | quote }}
    {{- end }}
  usages:
    - client auth
---
{{- /*  
  reflect secret for cross-namespace replication
*/}}
{{- if and
    (and 
      (eq $db.bootstrap.mode "clone")
      (eq $db.bootstrap.clone.source "peer")
    )
    $db.bootstrap.clone.namespace
    }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $releaseName }}-db-clone-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "{{ $db.bootstrap.clone.namespace -}}
      / {{- $db.bootstrap.clone.name | default $releaseName -}} -db-replica-tls"
{{- end }}{{/* reflected secret */}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $releaseName }}-db-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  usages: [ client auth ]
  commonName: companies
  {{- if $db.generateIssuer }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ $releaseName }}-db-issuer
  {{- else }}
  issuerRef: {{ toYaml $db.caIssuer | nindent 4 }}
  {{- end }}
  secretName: {{ $releaseName }}-db-app-tls
  secretTemplate:
    labels:
      cnpg.io/reload: "true"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $releaseName }}-db
  namespace: {{ .Release.Namespace }}
  {{- /* Fencing mode */}}
  {{- if and (eq $db.bootstrap.mode "transition") (eq $db.bootstrap.transitionPhase "standby_fence") }}
  annotations:
    cnpg.io/fencedInstances: '["*"]'
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- /*
    CNPG bug: while transitioning, the multitude of reconciliation errors caused
    by zalando incompatibilities before cleanup scripts get applied confuse the
    CNPG operator and cause the cluster to get stuck in an unrecoverable state
    as far as the operator can see. This is recoverable only if no other 
    instances are spawned while the first one gets cleaned up. After transition
    phase is complete (transitionPhase set to full or mode switched away from 
    "transition") we can allow more than one instance to be spawned. */}}
  {{- if and (eq $db.bootstrap.mode "transition") $db.bootstrap.transitionPhase }}
  instances: 1
  {{- else }}
  instances: {{ .Values.replicas.db }}
  {{- end }}
  imageName: {{ $db.image.registry -}} 
            / {{- $db.image.name -}} 
            : {{- $db.image.tag }}
  {{- if $db.image.pullPolicy }}
  imagePullPolicy: {{ $db.image.pullPolicy }}
  {{- end }}
  storage: {{ toYaml $db.volume | nindent 4 }}
  certificates:
    {{- if $db.generateIssuer }}
    serverCASecret: {{ $releaseName }}-db-ca
    serverTLSSecret: {{ $releaseName }}-db-ca
    clientCASecret: {{ $releaseName }}-db-ca
    {{- else }}
    serverCASecret: {{ $releaseName }}-db-cert
    serverTLSSecret: {{ $releaseName }}-db-cert
    clientCASecret: {{ $releaseName }}-db-cert
    {{- end }}
    replicationTLSSecret: {{ $releaseName }}-db-replica-tls
  postgresql:
    pg_hba:
    - hostssl companies all all cert
    parameters: {{ toYaml $db.parameters | nindent 6}}
  {{- with .Values.resources.db }}
  resources: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- 
    $templateStr := tpl $db.template (
      dict "Release" .Release "Values" .Values "Chart" .Chart "db" $db
          "Template" .Template "releaseName" $releaseName
    )
  }}
  {{- $templateDict := fromYaml $templateStr -}}
  {{- $templateDict = mergeOverwrite $templateDict 
        ($db.overrides | default dict) -}}
  {{ $templateDict | toYaml | nindent 2 }}
  {{- with $db.affinity }}
  affinity: {{ toYaml . | nindent 4 }}
  {{- end }}
  monitoring:
    enablePodMonitor: {{ $db.monitoring }}
{{- with $db.backup }}
{{- if and .s3.enabled .schedule }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ $releaseName }}-db-scheduled-backup
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  cluster:
    name: {{ $releaseName }}-db
  schedule: {{ .schedule | quote }}
  backupOwnerReference: self
{{- end }}{{ end }}{{/* s3 enabled, schedule, backup */}}
{{- end }}
