{{- if .Values.ingress.enabled -}}
{{- $name := include "companies.releaseName" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "companies.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range default .Values.global.companies.hostnames .Values.ingress.hostnames }}
  - host: {{ . | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ $name }}-api
            port:
              name: api
        pathType: Prefix
        path: /api
      - backend:
          service:
            name: {{ $name }}-frontend
            port:
              name: frontend
        pathType: Prefix
        path: /
  {{- end }}
  {{- if default .Values.global.companies.tls .Values.ingress.tls }}
  tls:
  - hosts:
    {{ range default .Values.global.companies.hostnames .Values.ingress.hostnames }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ $name }}-cert
  {{- end }}
{{- end }}
