{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" ( include "companies.releaseName" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "companies.releaseName" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "companies.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if $secret.data }}
  {{ if $secret.data.auth_pkey }}
  auth_pkey: {{ $secret.data.auth_pkey }}
  {{- else }}
  auth_pkey: {{ genPrivateKey "rsa" | b64enc }}
  {{- end }}
  
  {{- if $secret.data.passrecovery }}
  passrecovery: {{ $secret.data.passrecovery }}
  {{- else }}
  passrecovery: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

  {{- if $secret.data.shared_secret }}
  shared_secret: {{ $secret.data.shared_secret }}
  {{- else }}
  shared_secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- else }}
  auth_pkey: {{ genPrivateKey "rsa" | b64enc }}
  passrecovery: {{ randAlphaNum 32 | b64enc }}
  shared_secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- $allowCloneFrom := .Values.db.allowCloneFrom }}
{{- if .Values.global }}
{{- $allowCloneFrom = .Values.global.allowCloneFrom }}
{{- end }}
{{- if $allowCloneFrom }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- $clusterName := include "companies.clusterName" . }}
  name: standby.{{ $clusterName }}.credentials
  labels:
    {{- include "companies.labels" . | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ $allowCloneFrom | quote }}
type: Opaque
data:
  username: {{ "standby" | b64enc }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "standby.%s.credentials" $clusterName ) }}
  {{- if $secret }}
  password: {{ $secret.data.password }}
  {{- else }}
  password: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end }}
