{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" ( include "companies.releaseName" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "companies.releaseName" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "companies.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if $secret.data }}
  {{ if $secret.data.auth_pkey }}
  auth_pkey: {{ $secret.data.auth_pkey }}
  {{- else }}
  auth_pkey: {{ genPrivateKey "rsa" | b64enc }}
  {{- end }}
  
  {{- if $secret.data.passrecovery }}
  passrecovery: {{ $secret.data.passrecovery }}
  {{- else }}
  passrecovery: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

  {{- if $secret.data.shared_secret }}
  shared_secret: {{ $secret.data.shared_secret }}
  {{- else }}
  shared_secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- else }}
  auth_pkey: {{ genPrivateKey "rsa" | b64enc }}
  passrecovery: {{ randAlphaNum 32 | b64enc }}
  shared_secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
