{{ if .Values.agency.cron.etripImport.enabled -}}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "agency.releaseName" . }}-etrip-import
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agency.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.agency.cron.etripImport.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        cronjob-name: etrip-import
        {{- include "agency.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            cronjob-name: etrip-import
            {{- include "agency.selectorLabels" . | nindent 12 }}
        spec:
          securityContext:
            fsGroup: 33
          restartPolicy: Never
          containers:
          - name: cron-etrip-import
            {{- include "agency.pod" . | indent 12 }}
            command: [ python3 ]
            args: 
            - -c 
            - |
              from agency.tasks import update_etrip_supplier
              from datetime import timedelta
              update_etrip_supplier(
                '/config/agency.ini#agency', 
                not_updated_for=timedelta(hours=24)
              )
            resources:
              {{- toYaml .Values.resources.cron | nindent 14 }}
          volumes:
          - name: config
            configMap:
              name: {{ include "agency.releaseName" . }}-config
              items:
              - key: agency.ini
                path: app/agency.ini
          {{- if eq .Values.db.provider "cnpg" }}
          - name: ssl-cert
            secret:
              secretName: {{ include "agency.releaseName" . }}-db-app-tls
              defaultMode: 416
          {{- end }}
{{- end }}
