{{ if .Values.agency.cron.exchangerate.enabled -}}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "agency.releaseName" . }}-exchangerate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agency.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.agency.cron.exchangerate.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        cronjob-name: exchangerate
        {{- include "agency.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            cronjob-name: exchangerate
            {{- include "agency.selectorLabels" . | nindent 12 }}
        spec:
          securityContext:
            fsGroup: 33
          restartPolicy: Never
          containers:
          - name: cron-exchangerate
            {{- include "agency.pod" . | indent 12 }}
            command: [ python3 ]
            args: 
            - -c 
            - |
              import agency.tasks
              {{- if eq .Values.agency.cron.exchangerate.source "bnr" }}
              agency.tasks.update_bnr_exchange('/config/agency.ini#agency')
              {{- else if eq .Values.agency.cron.exchangerate.source "floatrates" }}
              agency.tasks.update_floatrates_exchange('/config/agency.ini#agency',
                currencies=[
                  {{- range .Values.agency.cron.exchangerate.currencies -}}
                  "{{.}}",
                  {{- end -}}
                ])
              {{- end }}
            resources:
              {{- toYaml .Values.resources.cron | nindent 14 }}
          volumes:
          - name: config
            configMap:
              name: {{ include "agency.releaseName" . }}-config
              items:
              - key: agency.ini
                path: app/agency.ini
          {{- if eq .Values.db.provider "cnpg" }}
          - name: ssl-cert
            secret:
              secretName: {{ include "agency.releaseName" . }}-db-app-tls
              defaultMode: 416
          {{- end }}
{{- end }}
