{{ if .Values.agency.e_factura.enabled -}}
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: {{ include "agency.releaseName" . }}-efactura-refresh
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agency.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.agency.cron.e_factura.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        cronjob-name: efactura-refresh
        {{- include "agency.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            cronjob-name: efactura-refresh
            {{- include "agency.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
          - name: cron-efactura-refresh
            image: {{ .Values.image.registry -}} /agency/server: {{- include "agency.serverImageTag" . }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            securityContext:
              allowPrivilegeEscalation: false
              runAsUser: 100
              runAsGroup: 101
            volumeMounts:
            - mountPath: /config
              name: config
              subPath: app
            env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: 
                    name: agency.{{ include "agency.clusterName" . }}.credentials
                    key: password
            - name: CONFIG_PATH
              value: /config/agency.ini
            command: [ python3 ]
            args: 
            - -c 
            - |
              from agency.tasks import e_factura_refresh_tokens
              from datetime import timedelta
              e_factura_refresh_tokens ('/config/agency.ini#agency')
            resources:
              {{- toYaml .Values.resources.cron | nindent 14 }}
          volumes:
          - name: config
            configMap:
              name: {{ include "agency.releaseName" . }}-config
              items:
              - key: agency.ini
                path: app/agency.ini
{{- end }}
