apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "agency.clusterName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.db.controller }}
  annotations:
    acid.zalan.do/controller: {{ .Values.db.controller }}
  {{- end }}
  labels:
    {{- include "agency.labels" . | nindent 4 }}
spec:
  teamId: {{ .Values.db.teamId }}
  volume: {{ toYaml .Values.db.volume | nindent 4 }}
  numberOfInstances: {{ .Values.replicas.db }}
  users:
    agency: []
  databases:
    agency: agency
  postgresql:
    version: {{ .Values.db.version | quote }}
    parameters: {{ toYaml .Values.db.parameters | nindent 6 }}
  {{- if .Values.resources.db }}
  resources: {{ toYaml .Values.resources.db | nindent 4 }}
  {{- end }}
  {{- with .Values.db.clone }}
  clone: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.db.standby }}
  {{- if .enabled }}
  standby:
    s3_wal_path: s3://{{ .bucket }}/spilo/{{ .name | default (include "agency.clusterName" $) }}/{{ .uid }}/wal/{{ $.Values.db.version }}
  {{- end }}
  {{- end }}
