{{- if .Values.ingress.enabled -}}
{{- $name := include "agency.releaseName" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agency.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- with default .Values.global.agency.admin .Values.ingress.admin }}
  {{- range .hostnames }}
  - host: {{ . | quote }}
    http:
      paths:
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: {{ $name }}-admin
            port:
              name: api
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ $name }}-admin
            port: 
              name: admin

  {{- end }}{{ end }}
  {{- with default .Values.global.agency.rescheck .Values.ingress.rescheck }}
  {{- range .hostnames }}
  - host: {{ . | quote }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ $name }}-admin
            port: 
              name: rescheck
  {{- end }}{{ end }}
  {{- if default .Values.global.agency.tls .Values.ingress.tls }}
  tls:
  - hosts:
    {{ with default .Values.global.agency.admin .Values.ingress.admin }}
    {{ range .hostnames }}
    - {{ . | quote }}
    {{- end }}{{ end }}
    {{- with default .Values.global.agency.rescheck .Values.ingress.rescheck }}
    {{- range .hostnames }}
    - {{ . | quote }}
    {{- end }}{{ end }}
    secretName: {{ $name }}-cert
  {{- end }}
{{- end }}
