{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" (include "agency.releaseName" .) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agency.releaseName" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agency.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if $secret.data }}
  session: {{ $secret.data.session }}
  {{- else }}
  session: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if $secret.data }}
  passrecovery: {{ $secret.data.passrecovery }}
  {{- else }}
  passrecovery: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if and .Values.agency.companies.enabled (or (not .Values.agency.companies.shared_secret.source) (not .Values.companies.enabled) ) }}
  shared_secret: {{ .Values.agency.companies.shared_secret.value }}
  {{- end }}
