{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" (include "agency.releaseName" .) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agency.releaseName" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agency.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if $secret.data }}
  session: {{ $secret.data.session }}
  {{- else }}
  session: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if $secret.data }}
  passrecovery: {{ $secret.data.passrecovery }}
  {{- else }}
  passrecovery: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if and (not .Values.companies.enabled)
    .Values.agency.companies.enabled
    .Values.agency.companies.shared_secret.value
    (not .Values.agency.companies.shared_secret.source)
  }}
  shared_secret: {{ .Values.agency.companies.shared_secret.value | b64enc }}
  {{- end }}
{{- $allowCloneFrom := .Values.db.allowCloneFrom }}
{{- if .Values.global }}
{{- $allowCloneFrom = .Values.global.allowCloneFrom }}
{{- end }}
{{- if $allowCloneFrom }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- $clusterName := include "agency.clusterName" . }}
  name: standby.{{ $clusterName }}.credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agency.labels" . | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ $allowCloneFrom | quote }}
type: Opaque
data:
  username: {{ "standby" | b64enc }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "standby.%s.credentials" $clusterName ) }}
  {{- if $secret }}
  password: {{ $secret.data.password }}
  {{- else }}
  password: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end }}
