apiVersion: v1
kind: Service
metadata:
  name: {{ include "agency.releaseName" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agency.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  ports:
  - name: api
    port: 6543
    targetPort: api
  - name: admin
    port: 80
    targetPort: admin
  {{- if .Values.agency.rescheck }}
  - name: rescheck
    port: 81
    targetPort: rescheck
  {{- end }}
  selector:
    {{- include "agency.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  type: ClusterIP

